all:
	cd estructurasDeDatos; make Data
	cd common; make common
	cd client; make client
	cd server; make server
	

clean:
	cd common; make clean
	cd estructurasDeDatos; make clean
	cd client; make clean
	cd server; make clean
	
	
